# Generated by Django 4.1.3 on 2022-11-22 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cost_oto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phi_su_dung_duong_bo', models.IntegerField()),
                ('bao_hiem_trach_nhiem', models.IntegerField()),
                ('phi_dk_bien_so', models.IntegerField()),
                ('phi_dang_kiem', models.IntegerField()),
                ('noi_dk', models.CharField(max_length=255)),
                ('phi_truoc_ba', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='info_oto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenxe', models.CharField(max_length=255)),
                ('ten_xe', models.CharField(max_length=255)),
                ('danh_sach_hinh', models.CharField(max_length=500)),
                ('mo_ta_chi_tiet', models.CharField(max_length=3000)),
                ('gia_niem_uyet', models.IntegerField()),
                ('dong_co', models.CharField(max_length=255)),
                ('cong_xuat', models.CharField(max_length=255)),
                ('momen_xoan', models.CharField(max_length=255)),
                ('ho_so', models.CharField(max_length=255)),
                ('he_dan_dong', models.CharField(max_length=255)),
                ('so_cho', models.IntegerField()),
            ],
        ),
    ]
